
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 20

trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - mallet_finger
  constraints:
    mallet_finger:
      trajectory: 2.0
      goal: 2.0

position_controller:
  type: "position_controllers/JointPositionController"
  joint: mallet_finger