joint_limits:
  mallet_servo:
    has_position_limits: true
    # ! To be set correctly
    min_position: 0
    max_position: 6.28
    # ? Should we set these? 
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    has_jerk_limits: false