joint_limits:
  mallet_servo:
    has_position_limits: true
    # ! To be set correctly
    min_position: 0
    max_position: 1.57
    has_velocity_limits: false
    has_acceleration_limits: false
    has_jerk_limits: false