joint_limits:
  mallet_finger:
    has_position_limits: true
    min_position: 0
    max_position: 1.602
    has_velocity_limits: true
    # radians / sec
    max_velocity: 7.0
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: false