#goal definition
marimbabot_msgs/HitSequenceElement[] hit_sequence_elements # HitSequenceElement that should be played, definition in provided in marimbabot_msgs/HitSequenceElement.msg

#result definition
---
bool playing # whether marimbabot is currently playing
bool planning_successful # whether the planning of marimbabot was successful

#feedback
---
bool playing # whether marimbabot is currently (still) playing, i.e. the goal is still active
