#goal definition
marimbabot_msgs/HitSequenceElement[] hit_sequence_elements # HitSequenceElement that should be played, definition in provided in marimbabot_msgs/HitSequenceElement.msg

#result definition
---
bool success # whether the goal was successfully achieved

# Define the error codes
uint16 SUCCESS = 0
uint16 PLANNING_FAILED = 1
uint16 EXECUTION_FAILED = 2

uint16 error_code # error code in case of failure (see above)

#feedback
---
bool playing # whether marimbabot is currently (still) playing, i.e. the goal is still active
