#goal definition
std_msgs/String lilypond_string # sequence to be played including dynamics and tempo
---
#result definition
std_msgs/String lilypond_string # sequence that was actually played
int32 total_of_notes_played # number of notes played in total
bool success # whether bot executed the goal successfully
---
#feedback
std_msgs/String played_lilypond_sequence # sequence that was played so far
int32 current_number_of_notes_played # update on the amount of notes played