# elbow.yaml
# Specifies the upper and lower limits of ur5 joints in the urdf.
# elbow_up restricts the arm to move like a marimba player.

# Limits that align with the robots joint limits (+/- 2*pi) may allow
# joint configurations that lead to protective stop.
wrist_2_joint:
    lower: -0.5
    upper: 0.5