controller_list:
  - joint_state_controller: {}
  #   type: joint_state_controller/JointStateController
  #   publish_rate: 100

  # - gripper_controller:
  #   type: effort_controllers/JointTrajectoryController
  #   joints:
  #     - s_model_finger_1_joint_1
  #     - s_model_finger_1_joint_2
  #     - s_model_finger_1_joint_3
  #     - s_model_finger_2_joint_1
  #     - s_model_finger_2_joint_2
  #     - s_model_finger_2_joint_3
  #     - s_model_finger_middle_joint_1
  #     - s_model_finger_middle_joint_2
  #     - s_model_finger_middle_joint_3
  #     - s_model_palm_finger_1_joint
  #     - s_model_palm_finger_2_joint
  #   gains:
  #     s_model_finger_1_joint_1: { p: 100.0, d: 0.0, i: 10.0, i_clamp: 20.0 }
  #     s_model_finger_1_joint_2: { p: 100.0, d: 0.0, i: 10.0, i_clamp: 20.0 }
  #     s_model_finger_1_joint_3: { p: 100.0, d: 0.0, i: 10.0, i_clamp: 20.0 }
  #     s_model_finger_2_joint_1: { p: 100.0, d: 0.0, i: 10.0, i_clamp: 20.0 }
  #     s_model_finger_2_joint_2: { p: 100.0, d: 0.0, i: 10.0, i_clamp: 20.0 }
  #     s_model_finger_2_joint_3: { p: 100.0, d: 0.0, i: 10.0, i_clamp: 20.0 }
  #     s_model_finger_middle_joint_1: { p: 100.0, d: 0.0, i: 10.0, i_clamp: 20.0 }
  #     s_model_finger_middle_joint_2: { p: 100.0, d: 0.0, i: 10.0, i_clamp: 20.0 }
  #     s_model_finger_middle_joint_3: { p: 100.0, d: 0.0, i: 10.0, i_clamp: 20.0 }
  #     s_model_palm_finger_1_joint: { p: 100.0, d: 0.0, i: 10.0, i_clamp: 20.0 }
  #     s_model_palm_finger_2_joint: { p: 100.0, d: 0.0, i: 10.0, i_clamp: 20.0 }
  #   constraints:
  #     goal_time: 0.6
  #     stopped_velocity_tolerance: 0.05
  #     s_model_finger_1_joint_1: { trajectory: 0.1, goal: 0.01 }
  #     s_model_finger_1_joint_2: { trajectory: 0.1, goal: 0.01 }
  #     s_model_finger_1_joint_3: { trajectory: 0.1, goal: 0.01 }
  #     s_model_finger_2_joint_1: { trajectory: 0.1, goal: 0.01 }
  #     s_model_finger_2_joint_2: { trajectory: 0.1, goal: 0.01 }
  #     s_model_finger_2_joint_3: { trajectory: 0.1, goal: 0.01 }
  #     s_model_finger_middle_joint_1: { trajectory: 0.1, goal: 0.01 }
  #     s_model_finger_middle_joint_2: { trajectory: 0.1, goal: 0.01 }
  #     s_model_finger_middle_joint_3: { trajectory: 0.1, goal: 0.01 }
  #   stop_trajctory_duration: 0.5
  #   state_publish_rate: 100
  #   action_monitor_rate: 20

  # - arm_controller:
  #   # type: position_controllers/JointTrajectoryController
  #   type: effort_controllers/JointTrajectoryController
  #   joints:
  #     - ur5_shoulder_pan_joint
  #     - ur5_shoulder_lift_joint
  #     - ur5_elbow_joint
  #     - ur5_wrist_1_joint
  #     - ur5_wrist_2_joint
  #     - ur5_wrist_3_joint
  #   gains:
  #     ur5_shoulder_pan_joint: { p: 40000.0, d: 18.0, i: 8000.0, i_clamp: 4000.0 }
  #     ur5_shoulder_lift_joint: { p: 50000.0, d: 10.0, i: 7000.0, i_clamp: 10000.0 }
  #     ur5_elbow_joint: { p: 40000.0, d: 6.0, i: 4000.0, i_clamp: 10000.0 }
  #     ur5_wrist_1_joint: { p: 8000.0, d: 6.0, i: 300, i_clamp: 800.0 }
  #     ur5_wrist_2_joint: { p: 8000.0, d: 4.0, i: 300, i_clamp: 800.0 }
  #     ur5_wrist_3_joint: { p: 8000.0, d: 4.0, i: 300, i_clamp: 800.0 }
  #   constraints:
  #     goal_time: 0.6
  #     stopped_velocity_tolerance: 0.05
  #     ur5_shoulder_pan_joint: { trajectory: 0.1, goal: 0.01 }
  #     ur5_shoulder_lift_joint: { trajectory: 0.1, goal: 0.01 }
  #     ur5_elbow_joint: { trajectory: 0.1, goal: 0.01 }
  #     ur5_wrist_1_joint: { trajectory: 0.1, goal: 0.01 }
  #     ur5_wrist_2_joint: { trajectory: 0.1, goal: 0.01 }
  #     ur5_wrist_3_joint: { trajectory: 0.1, goal: 0.01 }
  #   stop_trajectory_duration: 0.5
  #   state_publish_rate: 100
  #   action_monitor_rate: 20

  # - marimba_bars_controller:
  #   type: 'effort_controllers/JointTrajectoryController'
  #   joints:
  #     - bar_A4/joint
  #     - bar_A5/joint
  #     - bar_A6/joint
  #     - bar_As4/joint
  #     - bar_As5/joint
  #     - bar_As6/joint
  #     - bar_B4/joint
  #     - bar_B5/joint
  #     - bar_B6/joint
  #     - bar_C4/joint
  #     - bar_C5/joint
  #     - bar_C6/joint
  #     - bar_C7/joint
  #     - bar_Cs4/joint
  #     - bar_Cs5/joint
  #     - bar_Cs6/joint
  #     - bar_D4/joint
  #     - bar_D5/joint
  #     - bar_D6/joint
  #     - bar_Ds4/joint
  #     - bar_Ds5/joint
  #     - bar_Ds6/joint
  #     - bar_E4/joint
  #     - bar_E5/joint
  #     - bar_E6/joint
  #     - bar_F4/joint
  #     - bar_F5/joint
  #     - bar_F6/joint
  #     - bar_Fs4/joint
  #     - bar_Fs5/joint
  #     - bar_Fs6/joint
  #     - bar_G4/joint
  #     - bar_G5/joint
  #     - bar_G6/joint
  #     - bar_Gs4/joint
  #     - bar_Gs5/joint
  #     - bar_Gs6/joint
  #   gains:
  #     bar_A4/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_A5/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_A6/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_As4/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_As5/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_As6/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_B4/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_B5/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_B6/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_C4/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_C5/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_C6/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_C7/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_Cs4/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_Cs5/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_Cs6/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_D4/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_D5/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_D6/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_Ds4/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_Ds5/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_Ds6/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_E4/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_E5/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_E6/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_F4/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_F5/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_F6/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_Fs4/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_Fs5/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_Fs6/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_G4/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_G5/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_G6/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_Gs4/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_Gs5/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #     bar_Gs6/joint: { p: 100, d: 0.3, i: 0.2, i_clamp: 4.0 }
  #   constraints:
  #     goal_time: 0.6
  #     stopped_velocity_tolerance: 0.05
  #     bar_A4/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_A5/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_A6/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_As4/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_As5/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_As6/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_B4/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_B5/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_B6/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_C4/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_C5/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_C6/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_C7/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_Cs4/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_Cs5/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_Cs6/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_D4/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_D5/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_D6/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_Ds4/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_Ds5/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_Ds6/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_E4/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_E5/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_E6/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_F4/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_F5/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_F6/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_Fs4/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_Fs5/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_Fs6/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_G4/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_G5/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_G6/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_Gs4/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_Gs5/joint: {trajectory: 0.1, goal: 0.01}
  #     bar_Gs6/joint: {trajectory: 0.1, goal: 0.01}
  #   stop_trajectory_duration: 0.5
  #   state_publish_rate:  100
  #   action_monitor_rate: 20 