# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_acceleration_scaling_factor: 1.0
default_velocity_scaling_factor: 0.2

max_arm_velocity: &max_arm_velocity
    max_velocity: 10.0

max_arm_acceleration: &max_arm_acceleration
    max_acceleration: 20.0

max_finger_velocity: &max_finger_velocity
    max_velocity: 0.5

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  s_model_finger_1_joint_1:
    has_velocity_limits: true
    <<: *max_finger_velocity
    has_acceleration_limits: false
    max_acceleration: 0
  s_model_finger_1_joint_2:
    has_velocity_limits: true
    <<: *max_finger_velocity
    has_acceleration_limits: false
    max_acceleration: 0
  s_model_finger_1_joint_3:
    has_velocity_limits: true
    <<: *max_finger_velocity
    has_acceleration_limits: false
    max_acceleration: 0
  s_model_finger_2_joint_1:
    has_velocity_limits: true
    <<: *max_finger_velocity
    has_acceleration_limits: false
    max_acceleration: 0
  s_model_finger_2_joint_2:
    has_velocity_limits: true
    <<: *max_finger_velocity
    has_acceleration_limits: false
    max_acceleration: 0
  s_model_finger_2_joint_3:
    has_velocity_limits: true
    <<: *max_finger_velocity
    has_acceleration_limits: false
    max_acceleration: 0
  s_model_finger_middle_joint_1:
    has_velocity_limits: true
    <<: *max_finger_velocity
    has_acceleration_limits: false
    max_acceleration: 0
  s_model_finger_middle_joint_2:
    has_velocity_limits: true
    <<: *max_finger_velocity
    has_acceleration_limits: false
    max_acceleration: 0
  s_model_finger_middle_joint_3:
    has_velocity_limits: true
    <<: *max_finger_velocity
    has_acceleration_limits: false
    max_acceleration: 0
  s_model_palm_finger_1_joint:
    has_velocity_limits: true
    <<: *max_finger_velocity
    has_acceleration_limits: false
    max_acceleration: 0
  s_model_palm_finger_2_joint:
    has_velocity_limits: true
    <<: *max_finger_velocity
    has_acceleration_limits: false
    max_acceleration: 0
  ur5_elbow_joint:
    has_velocity_limits: true
    <<: *max_arm_velocity
    has_acceleration_limits: true
    <<: *max_arm_acceleration
  ur5_shoulder_lift_joint:
    has_velocity_limits: true
    <<: *max_arm_velocity
    has_acceleration_limits: true
    <<: *max_arm_acceleration
  ur5_shoulder_pan_joint:
    has_velocity_limits: true
    <<: *max_arm_velocity
    has_acceleration_limits: true
    <<: *max_arm_acceleration
  ur5_wrist_1_joint:
    has_velocity_limits: true
    <<: *max_arm_velocity
    has_acceleration_limits: true
    <<: *max_arm_acceleration
  ur5_wrist_2_joint:
    has_velocity_limits: true
    <<: *max_arm_velocity
    has_acceleration_limits: true
    <<: *max_arm_acceleration
  ur5_wrist_3_joint:
    has_velocity_limits: true
    <<: *max_arm_velocity
    has_acceleration_limits: true
    <<: *max_arm_acceleration
