arm:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.02
  kinematics_solver_timeout: 0.02

  # bio_ik - gradient-decent without restarts - usually the best choice in weakly-constraint environments
  mode: gd_c

  # tracik - prefer closeby solutions
  #solve_type: Distance

  # ur kinematics - correct joint prefix
  #arm_prefix: ur5_

arm_mallet:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.02
  kinematics_solver_timeout: 0.02

  # bio_ik - gradient-decent without restarts - usually the best choice in weakly-constraint environments
  mode: gd_c

  # tracik - prefer closeby solutions
  #solve_type: Distance

  # ur kinematics - correct joint prefix
  #arm_prefix: ur5_
